In [55]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)

In [56]:
customer_data = pd.read_csv("../datasets/final-wms-customer-dataset.csv")
customer_data

customer_id          customer_name  branch_code branch_name  \
0               0        Purab Choudhary          100      Abohar   
1               1         Dhanuk Sawhney          101    Achalpur   
2               2       Vardaniya Master          102    Adilabad   
3               3  Aniruddh Ramakrishnan          103   Adityapur   
4               4             Azad Madan          104       Adoni   
...           ...                    ...          ...         ...   
9995         9995         Indrans Doctor          236  Davanagere   
9996         9996         Trisha Kadakia          237       Deesa   
9997         9997      Uthkarsh Randhawa          238    Dehradun   
9998         9998         Darshit Kurian          239       Dehri   
9999         9999       Mannat Ahluwalia          240       Delhi   

      customer_pan_card_no  customer_adhar_card_no date_of_birth  \
0               3800228131            249461771695    1979-12-03   
1               9373545607            368459715549    1996-07-21   
2               4835501359            418526656209    1975-12-22   
3               2342379187            465301930473    1961-08-05   
4               2851366087            862010278094    1993-09-09   
...                    ...                     ...           ...   
9995            3015535630            752914309300    2003-12-31   
9996            3755863133            800545040862    1990-12-23   
9997            3100866417            789209525837    2001-08-09   
9998            9469659231            435695433464    1976-01-21   
9999            1904076503            749725994919    1984-04-03   

                        address  name_of_city      state_name  state_code  \
0                 59\nRao Chowk             0          PUNJAB           3   
1          49/110\nBhatia Chowk             1     MAHARASHTRA          27   
2                   82/74, Kibe             2  ANDHRA PRADESH          28   
3              837\nDyal Circle             3       JHARKHAND          20   
4     H.No. 372, Krishnan Nagar             4  ANDHRA PRADESH          28   
...                         ...           ...             ...         ...   
9995       H.No. 52, Ghosh Path           136       KARNATAKA          29   
9996          83/078, Dani Road           137         GUJARAT          24   
9997                  52\nBassi           138     UTTARAKHAND           5   
9998           75/07\nKota Marg           139           BIHAR          10   
9999         87/430, Yogi Nagar           140    NCT OF DELHI           7   

     country  zip_code     mobile_no kyc_status  risk_id income_slab  \
0      India    400000  912710298956    Pending        2        High   
1      India    400001    8746797465    Pending        4      Medium   
2      India    400002  914450317183   Verified        2      Medium   
3      India    400003    6886199568    Pending        1        High   
4      India    400004  916136017468   Verified        4      Medium   
...      ...       ...           ...        ...      ...         ...   
9995   India    409995  911202428436   Verified        2        High   
9996   India    409996    6356049303   Rejected        3         Low   
9997   India    409997     233088153   Rejected        2        High   
9998   India    409998     894178229    Pending        2         Low   
9999   India    409999  916528032442   Rejected        1        High   

      kyc_number                         crn_unique_id account_type  \
0         982476  346a04c7-653d-4edd-a3cb-6d66ff3d6b76      Current   
1         817977  c68345e8-0de1-4c12-b8f5-540cdd885508      Savings   
2         861928  37ca78f0-82a4-461b-94cb-47eb4d5bb794      Savings   
3         492635  f969bd5c-1e62-4ad9-8456-b6e7bb882593      Current   
4         583144  8a10782a-4c35-4534-9c75-c7edfb0b0195      Savings   
...          ...                                   ...          ...   
9995      169228  a8ced964-e128-45ff-b6e5-58dca4188753      Current   
99

In [10]:
features = ["sip_amount", "networth", "age"]

In [11]:
data = customer_data[features]
data.head()

sip_amount    networth  age
0        0.00  4108881.34   79
1     4748.26   236515.43   19
2    29451.33  1285558.88   66
3    31966.45  7072801.65   36
4    76840.16  5380344.80   59

In [12]:
# scaling the data
data = ((data - data.min())/(data.max() - data.min())) * 9 + 1

In [13]:
data.head()

sip_amount  networth       age
0    1.000000  4.672946  9.854839
1    1.427444  1.167492  1.145161
2    3.651242  2.117137  7.967742
3    3.877656  7.356031  3.612903
4    7.917238  5.823937  6.951613

In [20]:
from sklearn.cluster import KMeans

In [21]:
kmeans = KMeans(3)
kmeans.fit(data)

/home/varunmore/Documents/poc-work/wms-customer-segmentation/wms/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)


KMeans(n_clusters=3)

In [22]:
centroids2 = kmeans.cluster_centers_
labels = kmeans.predict(data)

In [47]:
labels

array([2, 1, 0, ..., 1, 1, 1], dtype=int32)

In [23]:
centroids2

array([[6.84124637, 4.17353236, 8.02376572],
       [1.57537267, 2.52682566, 2.98512285],
       [1.80857425, 6.02763187, 6.34342136]])

In [24]:
pd.DataFrame(centroids2, columns=features).T

0         1         2
sip_amount  6.841246  1.575373  1.808574
networth    4.173532  2.526826  6.027632
age         8.023766  2.985123  6.343421

In [48]:
label_0 = customer_data[labels == 2][["sip_amount","networth","age" ]]
label_0

sip_amount    networth  age
0           0.00  4108881.34   79
3       31966.45  7072801.65   36
5       14656.33  6807438.89   36
11          0.00   593761.35   68
13      31531.34  5947938.35   39
...          ...         ...  ...
9916        0.00  4098981.79   47
9931     2907.64  3605366.11   45
9967     4748.28  4548783.05   47
9972     1553.81  3309741.47   47
9982     2975.52  4807247.99   47

[4281 rows x 3 columns]

In [52]:
test_data =label_0[label_0["sip_amount"] == 31966.45]
test_data

sip_amount    networth  age
3    31966.45  7072801.65   36

In [54]:
output = kmeans.predict(test_data)
output

array([2], dtype=int32)

In [43]:
import pickle

pickle.dump(kmeans, open('./models/customer-segmenation-model.pkl', 'wb'))

array([2], dtype=int32)